//Q7.Write a C Program that input values from m and n and display the values of the pythagorean triple generated by following formulas.
//Side1 = m^2 - n^2;
//Side2 = 2mn
//Hypotenuse = m^2  + n^2

#include<stdio.h>
#include<math.h>

void main()
{

  int m,n;
  printf("Enter the value of m:\n");
  scanf("%d",&m);
  printf("Enter the value of n:\n");
  scanf("%d",&n);

  int Side1 = (pow(m,2)) - (pow(n,2));
  int Side2 = 2 * m * n;
  int Hypotenuse = (pow(m,2)) + (pow(n,2));


  printf("SIDE 1 %d\n",Side1);
  printf("SIDE 2 %d\n",Side2);
  printf("Hypotenuse %d\n",Hypotenuse);


}